# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quadraticEquation.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17quadraticEquation.proto\"4\n\x11Quadratic_Request\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12\t\n\x01\x63\x18\x03 \x01(\x01\"&\n\x12Quadratic_Response\x12\x10\n\x08solution\x18\x01 \x01(\t2Y\n\x12Quadratic_Solution\x12\x43\n\x18Solve_Quadratic_Equation\x12\x12.Quadratic_Request\x1a\x13.Quadratic_Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quadraticEquation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUADRATIC_REQUEST']._serialized_start=27
  _globals['_QUADRATIC_REQUEST']._serialized_end=79
  _globals['_QUADRATIC_RESPONSE']._serialized_start=81
  _globals['_QUADRATIC_RESPONSE']._serialized_end=119
  _globals['_QUADRATIC_SOLUTION']._serialized_start=121
  _globals['_QUADRATIC_SOLUTION']._serialized_end=210
# @@protoc_insertion_point(module_scope)
